service: contact-form-service

custom:
  settings: ${file(settings.json)}
  customDomain:
    domainName: api.appfocused.com
    certificateName: "www.appfocused.com"
    basePath: "api"
    stage: ${self:provider.stage}
    createRoute53Record: true

plugins:
  - serverless-domain-manager
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.settings.NODE_ENV}
  region: eu-west-1
  environment:
    NODE_ENV: ${self:custom.settings.NODE_ENV}
    EMAIL: ${self:custom.settings.EMAIL}
    DOMAIN: ${self:custom.settings.DOMAIN}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

functions:
  send:
    handler: handler.send
    events:
      - http:
          path: email/send
          method: post
          cors: true
